### ISSUE TITLE
Tipos de Modals

### ISSUE THREAD

**Issue by aerendon** [jointDeveloper/web#15]
Consultar varios tipos de modals para elegir uno de acuerdo al estilo de la web 2017

**Comment by sebas095** [comment]
Opciones de tipo de modal:
* http://izimodal.marcelodolce.com/#modal-custom
* http://github.hubspot.com/vex/docs/welcome/
* [Otros](http://jster.net/tag/modal)

**Comment by aerendon** [comment]
Bootstrap:

- http://v4-alpha.getbootstrap.com/components/modal/

**Comment by aerendon** [comment]
Se selecciona _Izi Modal_
* http://izimodal.marcelodolce.com/#modal-custom
