### ISSUE TITLE
Introducción Acerca de

### ISSUE THREAD

**Issue by aerendon** [jointDeveloper/web#28]

**Comment by vanevela** [comment]
_Mi propuesta: (es una mezcla de todo lo que encontré escrito al respecto, es corta porque seguí el ejemplo de otras comunidades, siempre corto y directo)_

**Acerca de** 
jointDeveloper es una comunidad que busca interesar a mujeres y niñas en la tecnología y generar espacios que promuevan su participación en este campo  mediante el aprendizaje colectivo, compartiendo conocimientos y recursos técnicos con otras comunidades.

**Comment by carogomezt** [comment]
Me gusta mucho esta idea ☺️

**Comment by aerendon** [comment]
![image](https://cloud.githubusercontent.com/assets/14989202/24328877/8198e69e-11bb-11e7-9a78-59500e925039.png)
