### ISSUE TITLE
Cambiar filtros de imagenes 

### ISSUE THREAD

**Issue by vanevela** [jointDeveloper/web#30]
La imagen de introducción y el mosaico de eventos  "están muy rosados" jejeje tal vez se podría generar un mejor contraste con otro tipo de filtro.

**Comment by aerendon** [comment]
De momento hice un cambio en el filtro, tiene una capa de color #777

![image](https://cloud.githubusercontent.com/assets/14989202/24328309/91108ff6-11ab-11e7-9fa5-6c9c9115fb23.png)

**Comment by vanevela** [comment]
se ve muy bien... aunque no se ve el slogan, pero ya sería cosa de cambiarle el color de la letra...

**Comment by aerendon** [comment]
![image](https://cloud.githubusercontent.com/assets/14989202/24336433/dfdc860e-1254-11e7-8b5e-288a0708fe1b.png)
