### ISSUE TITLE
Cambiar slogan 

### ISSUE THREAD

**Issue by vanevela** [jointDeveloper/web#32]
Según la votación realizada en Slack el nuevo slogan de la comunidad es : Learning includes everyone
![screen shot 2017-03-24 at 4 52 33 pm](https://cloud.githubusercontent.com/assets/10872725/24314972/6567c9ae-10b2-11e7-8b6e-8112e6d11d9d.png)

**Comment by aerendon** [comment]
![slogan](https://cloud.githubusercontent.com/assets/14989202/24328213/4452f7dc-11a9-11e7-85e0-0eb64054c455.png)

**Comment by aerendon** [comment]
![image](https://cloud.githubusercontent.com/assets/14989202/24328855/ef412a04-11ba-11e7-8053-10f56e94b134.png)
